services:
  app:
    container_name: forms_app
    image: forms_app_image
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MONOREPOPORT: 5000
    ports:
      - "5000:5000"
    environment:
      - MONOREPOPORT=${MONOREPOPORT}
      - MONGODB_URI=${MONGODB_URI}